Repository jupyter/docker-stacks, pull requests merged in 2020-09, with the labels that each got.

#1158 Spark 3.0.1 -> fixes #1156
  base-notebook/test/test_container_options.py
  docs/using/specifics.md
  pyspark-notebook/Dockerfile
Labels: type:Bug

#1118 Fix python codestyle
  .flake8
  .pre-commit-config.yaml
  all-spark-notebook/test/test_spark_notebooks.py
  base-notebook/jupyter_notebook_config.py
  base-notebook/test/test_container_options.py
  base-notebook/test/test_pandoc.py
  conftest.py
  datascience-notebook/test/test_julia.py
  docs/conf.py
  pyspark-notebook/test/test_spark.py
  scipy-notebook/test/data/matplotlib_1.py
  scipy-notebook/test/test_pandas.py
  test/helpers.py
  test/test_packages.py
Labels: type:Maintenance

#1173 Fix bashate style issues
  .pre-commit-config.yaml
  base-notebook/fix-permissions
  minimal-notebook/hooks/run_hook
  r-notebook/hooks/run_hook
  tensorflow-notebook/hooks/run_hook
Labels: status:Ready to Merge
