Repository jupyter/docker-stacks, pull requests merged in 2020-08, with the labels that each got.

#1130 Removed optional texlive-fonts-extra
  minimal-notebook/Dockerfile
Labels: status:Ready to Merge

#1146 Resolve Docker lint (hadolint) errors
  .pre-commit-config.yaml
  examples/docker-compose/notebook/Dockerfile
  examples/make-deploy/Dockerfile
Labels: type:Maintenance

#1145 Resolves #1131: Allow alternative Spark version
  docs/using/specifics.md
  pyspark-notebook/Dockerfile
Labels: type:Enhancement
