Repository jupyter/docker-stacks, pull requests merged in 2020-04, with the labels that each got.

#1058 Housekeeping
  .travis.yml
  all-spark-notebook/Dockerfile
  base-notebook/Dockerfile
  datascience-notebook/Dockerfile
  r-notebook/Dockerfile
  scipy-notebook/Dockerfile
  test/helpers.py
Labels: status:Ready to Merge

#1061 [DOC] #1060 Fix conda command to create env
  docs/using/recipes.md
Labels: status:Ready to Merge

#1059 add vim to minimal-notebook (cf. issue 779)
  docs/using/selecting.md
  minimal-notebook/Dockerfile
Labels: status:Ready to Merge

#1067 Added basic tests on some important components
  scipy-notebook/test/test_pandas.py
  tensorflow-notebook/test/test_tensorflow.py
Labels: status:Ready to Merge

#1070 [DOC] Selecting image doc minor fixes
  docs/using/selecting.md
Labels: status:Ready to Merge

#1069 add pytables and bottleneck
  docs/using/selecting.md
  scipy-notebook/Dockerfile
  test/test_packages.py
Labels: status:Ready to Merge, type:Enhancement

#1074 ihaskell-notebook binder urlpath
  docs/using/selecting.md
Labels: status:Ready to Merge, tag:Documentation
