Repository jupyter/docker-stacks, pull requests merged in 2020-11, with the labels that each got.

#1190 Adding kotlin-notebook to community stacks list
  docs/using/selecting.md
Labels: tag:Community Stack

#1186 [Bug fix] Create home directory before changing ownership
  base-notebook/start.sh
  base-notebook/test/test_container_options.py
Labels: status:Ready to Merge, type:Bug

#1189 Switch from Miniconda to Miniforge
  base-notebook/Dockerfile
  docs/using/common.md
  docs/using/selecting.md
  test/helpers.py
  test/test_packages.py
Labels: status:Ready to Merge, type:Enhancement

#1188 Remove emacs and jed from the minimal image
  docs/using/selecting.md
  minimal-notebook/Dockerfile
Labels: type:Enhancement

#1192 Improve spark installation
  docs/using/specifics.md
  pyspark-notebook/Dockerfile
  pyspark-notebook/test/test_spark.py
Labels: type:Enhancement
