Repository jupyter/docker-stacks, pull requests merged in 2020-05, with the labels that each got.

#1075 Matplotlib tests + helpers methods
  Makefile
  minimal-notebook/test/test_nbconvert.py
  scipy-notebook/test/data/matplotlib_1.py
  scipy-notebook/test/test_matplotlib.py
  scipy-notebook/test/test_pandas.py
  tensorflow-notebook/test/test_tensorflow.py
  test/test_notebook.py
Labels: status:Ready to Merge, type:Maintenance

#1076 Regular update 2020 W18
  all-spark-notebook/Dockerfile
  base-notebook/Dockerfile
  datascience-notebook/Dockerfile
  datascience-notebook/test/test_julia.py
  r-notebook/Dockerfile
  scipy-notebook/Dockerfile
Labels: status:Ready to Merge, type:Enhancement

#1065 Changed the regular expression in start.sh that reads the /etc/sudoer…
  base-notebook/start.sh
Labels: status:Ready to Merge, type:Bug

#1068 Add a recipe for auto_sklearn
  docs/using/recipes.md
Labels: status:Ready to Merge, tag:Recipe

#1082 Use pip --no-cache-dir to install tensorflow
  tensorflow-notebook/Dockerfile
Labels: status:Ready to Merge, type:Enhancement

#1078 Fix #1077
  base-notebook/test/test_container_options.py
  docs/using/common.md
Labels: status:Ready to Merge, tag:Documentation

#1098 Follow-on PR #911: Spark documentation rework
  all-spark-notebook/test/data/local_pyspark.ipynb
  all-spark-notebook/test/data/local_sparkR.ipynb
  all-spark-notebook/test/data/local_sparklyr.ipynb
  all-spark-notebook/test/data/local_spylon.ipynb
  all-spark-notebook/test/data/local_toree.ipynb
  all-spark-notebook/test/test_spark_notebooks.py
  docs/using/specifics.md
Labels: tag:Documentation
