Repository jupyter/docker-stacks, pull requests merged in 2021-05, with the labels that each got.

#1279 Install spark from archive.apache.org to be able to use old versions
  docs/using/specifics.md
  pyspark-notebook/Dockerfile
Labels: status:Ready to Merge

#1283 Update Ubuntu 20.04 LTS (Focal Fossa) base image
  base-notebook/Dockerfile
Labels: status:Ready to Merge

#1285 Update JupyterHub to 1.4.0
  base-notebook/Dockerfile
Labels: status:Ready to Merge

#1288 Use hadolint from pre-commit
  .github/workflows/docker.yml
  .pre-commit-config.yaml
  Makefile
  binder/Dockerfile
  docs/contributing/lint.md
Labels: tag:Upstream, type:Enhancement

#1295 Fix dead links in docs
  docs/contributing/features.md
  docs/contributing/issues.md
  docs/contributing/stacks.md
  docs/contributing/tests.md
  docs/using/common.md
  docs/using/selecting.md
Labels: tag:Documentation

#1274 Fix Docker Cloud -> Docker Hub and GitHub Actions related changes
  docs/contributing/stacks.md
  docs/maintaining/tasks.md
  docs/using/selecting.md
Labels: tag:Documentation

#1302 Added Pacific Research Platform (PRP) managed images registry to community
  docs/using/selecting.md
Labels: tag:Community Stack

#1294 Make markdown files look prettier using prettier :)
  .github/issue_template.md
  .pre-commit-config.yaml
  CONTRIBUTING.md
  LICENSE.md
  README.md
  docs/contributing/issues.md
  docs/contributing/lint.md
  docs/contributing/stacks.md
  docs/contributing/translations.md
  docs/using/common.md
  docs/using/specifics.md
  examples/docker-compose/README.md
  examples/make-deploy/README.md
  examples/openshift/README.md
  examples/source-to-image/README.md
Labels: type:Maintenance

#1290 Removal of outdated ppc64le arch Dockerfile
  .pre-commit-config.yaml
  Makefile
  base-notebook/Dockerfile.ppc64le
  base-notebook/Dockerfile.ppc64le.patch
Labels: type:Maintenance
